name: Gradle Profiler

on:
  schedule:
#    - cron: '0 18 * * *' # Runs every day at 18:00 UTC
    - cron: '0 2 * * 0' # Runs every Sunday at 2 AM UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  profile_and_upload:
    name: Run Gradle Profiler and Upload to New Relic
    runs-on: macos-latest

    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@main
      - uses: actions/checkout@v6
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # v5.0.0

      - uses: tecolicom/actions-use-homebrew-tools@v1
        with:
          tools: gradle-profiler

      - name: Run ProfilerPlugin
        env:
          newRelicLicenseKey: ${{ secrets.NEW_RELIC_LICENSE_KEY }}
        run: ./gradlew profileAndUpload "-PnewRelicApiKey=$newRelicLicenseKey"
